const fs = require('fs')
const path = require('path')
const source = require('./source.js')
const {treeParser} = require('../src/index.js')
fs.writeFileSync(path.join(__dirname,'../source/tree.json'),JSON.stringify(treeParser(source)))